### ISSUE TITLE
Criar página de gerenciamento de angedamentos

### ISSUE THREAD

**Issue by viniferraria** [matheusaf/webarber-frontend#22]
Um usuário do sistema pode alterar, cancelar e visualizar os seus agendamentos.

**Comment by viniferraria** [comment]
🍕🥵😬🤥

**Comment by Lucas-ef** [comment]
Mocks de telas criados.
https://www.figma.com/file/yw6dPoCBMuCzGWYBpbda4V/Untitled?node-id=0%3A1
